### ISSUE TITLE
What should the curriculum be?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/managing-research-software-projects#1]
The design notes in `_extras/design.md` (rendered at https://swcarpentry.github.io/managing-research-software-projects/design/) are a first cut at what this one-day class should cover. What's missing?  What's unnecessary?  What else do you think?  Please add comments to this issue, and @gvwilson will summarize by Aug 8 or 9 (2016). Please also see the other issues people have opened in this repo with larger comments (and feel free to open more).

**Comment by jpellman** [comment]
Greater awareness of the [Mythical Man Month](https://en.wikipedia.org/wiki/The_Mythical_Man-Month) would be widely beneficial in the research software community.

**Comment by jpellman** [comment]
More broadly, it might be good to go over some general project management principles (limiting scope, etc).  Nick Jenkins wrote [a particularly succinct Creative Commons-licensed primer](http://www.nickjenkins.net/prose/projectPrimer.pdf) on a couple important topics with a bit of a slant towards software engineering that might be helpful for this.

**Comment by benlaken** [comment]
Perhaps it is too much/overly ambitious, but maybe at some point mention Docker or Vagrant?

**Comment by gvwilson** [comment]
I've found that things mentioned in passing don't stick - if they should 
be covered (and I agree they're important these days), we should devote 
half an hour and a practical exercise.  What would you cover in that time?

**Comment by benlaken** [comment]
Well Vagrant might be more useful in the context of a research software project, where you want to ensure that all team members are working with the same environment/dependencies. But if they have only 30 mins, and they try and vagrant up for the first time, it might potentially take 20 mins!

Maybe a more practical first step is to specify their python environment with a requirements.txt file. Perhaps have them work in pairs, get one of them to install a package from pip and make/update a requirements.txt file (I guess there will already be one if you are planning on showing them how to package their code with a setup.py file?), add/push the updated requirements.txt to their repo, and then have the second person pull down the changes and pip install from the requirements.txt file.

It might be a good way to start them thinking about reproducible environments (as well as code). (Maybe you had already thought about doing something similar though, as you have Travis one of the tools you want to use in the lesson.)

**Comment by gvwilson** [comment]
Breaking into separate issues.
