### ISSUE TITLE
Publications/citations

### ISSUE THREAD

**Issue by IanHawke** [swcarpentry/managing-research-software-projects#35]
The design document says the audience is RSEs, who I'd expect to work with academics, who will care about that most precious of currencies: papers. These are briefly mentioned in the Building a community section, but nowhere else? 

I'd suggest adding a comment in the introduction, on "What does "done" look like", which could be reinforced in the community section, noting that having

* a citable "publication", plus
* clear guidance in the documentation as to how the project should be cited

are both important for getting academics on board. It may also be worth noting that some overlay journals like [JOSS](http://joss.theoj.org/) or [JORS](http://openresearchsoftware.metajnl.com/) are set up to work well with the management workflow described here.

**Comment by danielskatz** [comment]
I might rephrase this slightly and say that there should be a section (or at least a subsection) that talks about "how to tell users and developers about how to credit this work when they use it"

**Comment by gvwilson** [comment]
Added a placeholder in ccf653d - a PR with a fuller description would be very welcome.

**Comment by danielskatz** [comment]
This commit (https://github.com/swcarpentry/managing-research-software-projects/commit/ccf653df836a7993d91ce2639e3e869a5363775a) doesn't really address this issue.

**Comment by IanHawke** [comment]
I think @gvwilson meant 4add15d8789234220b724daaad211810ecd1b0fb which adds a comment to the introduction. I'll look at the section on community.

**Comment by danielskatz** [comment]
right - ok, that seems good as a placeholder.
