### ISSUE TITLE
Clearly identify team members

### ISSUE THREAD

**Issue by zzcgujl** [swcarpentry/managing-research-software-projects#4]
Idtentify who the research active team members are and what software development they are contributing plus what they need to get out of it in what time frame along with ideintifying who the research inactive team members and what they are contributing plus what they need to get out of it in what time frame.
1, Make it clear to research active members that you respect their research confidentiality and make an agreement about what is sensitive to their research and what is not. Make any agreements about when, if and how long data and software needs to be kept confidential.
2, Make agreements about when and how software changes will be integrated. You may want to fork off some researchers (particualrly inexperienced ones or ones who are making dramatic changes to the codes, perhaps parallelising it, so that they can learn on their fork) and integrate their work comes later.
3, Once you understand the context of those developing and using the code you can develop a plan.

**Comment by gvwilson** [comment]
As per #3, this pushes the lesson toward "building digital scientific instruments" rather than exploratory coding - which is OK, we just need to make it explicit.

**Comment by gvwilson** [comment]
Closed by 8a41884
